In [7]:
import numpy as np

In [8]:
a = np.array([[0],[0],[1]])
a

array([[0],
       [0],
       [1]])

In [9]:
M = np.array([[1/np.sqrt(2),0,1/np.sqrt(2)],[0,1,0],[-1/np.sqrt(2),0,1/np.sqrt(2)]])
M@a

array([[0.70710678],
       [0.        ],
       [0.70710678]])

In [10]:
np.linalg.inv(M)@a### pendiente: invertir unitario de local a W

array([[-0.70710678],
       [ 0.        ],
       [ 0.70710678]])

In [11]:
import quaternionic

In [14]:
θ = np.pi/6
q1 = quaternionic.array([np.sqrt(2)/2, np.sqrt(2)/2, 0, 0])
v1 = quaternionic.array([0, 1, 0, 1])
q3 = quaternionic.array([np.sqrt(2)/2, -np.sqrt(2)/2, 0, 0])
T1 = q1*v1*np.conjugate(q1)
T1

quaternionic.array([ 0.,  1., -1.,  0.])